USE scrum;
DROP TABLE info;
CREATE TABLE info (
    naam VARCHAR(30) NOT NULL,
    issue VARCHAR(500) NOT NULL,
    lokaal VARCHAR(20) NULL,
    ArrivalDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL
);
DROP TABLE COACHES;
CREATE TABLE COACHES(
naam varchar(30) NOT NULL,
id INT AUTO_INCREMENT PRIMARY KEY NOT NULL
);

INSERT INTO COACHES (naam, id)
VALUES ('Ties', NULL), ('Klaas', NULL);m 4', curdate());
